language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: dgjUnUh3jwndStbkZKpGBML6c160rlWiU+F+PRXwrrfN+3HOJo0Vsu62r7F93BT58lEJR7Lj29x9Dw6ZxdQSFh/N5FzN04gvrUhW3St+4aYEVCGQ+Aq04q/Nmgkf7aBrRtF8cQzCzUf9L14FWXXCWF6Qd+HHAiu3vz9rq8ySN9q9VGCzverQ5OIkMwHcwL+Jorlk9h1wTg9pgqvQPJ8RgWIfCO4q3hSYg9Czaqf+74DrOt9mdfByQSajOUAVXK92ssvqbaWtwEqL/PzTwtNHK4n/TOmxcTlg9oKBy07mAaUeHJRbFujWcDSyt4GTo18I9RpjKvXQdjAZFMUTd78Q365Io1eSals8atMyWPYAwpwHVFj4qqCp5sNwuWltZEibageflwGRLBL71IDWU+YRyTQ7+SREK+WodOzm+EY7S248f/+Dcdyv6SCsaWWTGOiVX9sO6Mv01Og+cGr2DT4oocfBSuvEW5//t1r4ah317HQRuAEzvZUWOSj+6y3cL0BUtspLgV/YDQ3vJ++X1V5tteg0EBjWXiSZiXshPAe4G3J9aruAKjqXLS0Xmd2rM5okqBkACQlx12v+7m42jLehf6cCbKaH9f35zK3aRv5K9vy0qi5KkHGuT4m1cmYL3XvBbGUsdDRTfzcDLvxUeSElbt6V2ZftaI8HzfM+jdTIJi4=
  file:
    - "hast-util-labelable.js"
    - "hast-util-labelable.min.js"
  on:
    tags: true
